import { CoverLetterTemplate } from '@/types/coverLetter';

export const coverLetterTemplates: CoverLetterTemplate[] = [
  {
    id: 'professional-traditional',
    name: 'Professional Traditional',
    description: 'Classic business letter format, perfect for corporate positions',
    category: 'professional',
    style: {
      fontSize: '11pt',
      fontFamily: 'Times New Roman, serif',
      lineHeight: '1.5',
      paragraphSpacing: '1rem',
      headerStyle: 'traditional',
      layout: 'standard',
    },
    sections: {
      header: true,
      date: true,
      recipient: true,
      salutation: true,
      opening: true,
      body: true,
      closing: true,
      signature: true,
    },
    tone: 'formal',
  },
  {
    id: 'professional-modern',
    name: 'Professional Modern',
    description: 'Contemporary design with clean lines for modern companies',
    category: 'professional',
    style: {
      fontSize: '11pt',
      fontFamily: 'Arial, sans-serif',
      lineHeight: '1.6',
      paragraphSpacing: '1.2rem',
      headerStyle: 'modern',
      layout: 'standard',
    },
    sections: {
      header: true,
      date: true,
      recipient: true,
      salutation: true,
      opening: true,
      body: true,
      closing: true,
      signature: true,
    },
    tone: 'formal',
  },
  {
    id: 'creative-bold',
    name: 'Creative Bold',
    description: 'Eye-catching design for creative industries and startups',
    category: 'creative',
    style: {
      fontSize: '10.5pt',
      fontFamily: 'Helvetica, sans-serif',
      lineHeight: '1.5',
      paragraphSpacing: '1rem',
      headerStyle: 'modern',
      layout: 'two-column',
    },
    sections: {
      header: true,
      date: false,
      recipient: true,
      salutation: true,
      opening: true,
      body: true,
      closing: true,
      signature: true,
    },
    tone: 'enthusiastic',
  },
  {
    id: 'executive-premium',
    name: 'Executive Premium',
    description: 'Elegant and sophisticated for senior-level positions',
    category: 'executive',
    style: {
      fontSize: '11pt',
      fontFamily: 'Georgia, serif',
      lineHeight: '1.7',
      paragraphSpacing: '1.3rem',
      headerStyle: 'traditional',
      layout: 'standard',
    },
    sections: {
      header: true,
      date: true,
      recipient: true,
      salutation: true,
      opening: true,
      body: true,
      closing: true,
      signature: true,
    },
    tone: 'confident',
  },
  {
    id: 'technical-precise',
    name: 'Technical Precise',
    description: 'Clean and structured for tech and engineering roles',
    category: 'technical',
    style: {
      fontSize: '11pt',
      fontFamily: 'Calibri, sans-serif',
      lineHeight: '1.5',
      paragraphSpacing: '1rem',
      headerStyle: 'minimal',
      layout: 'standard',
    },
    sections: {
      header: true,
      date: true,
      recipient: true,
      salutation: true,
      opening: true,
      body: true,
      closing: true,
      signature: true,
    },
    tone: 'formal',
  },
  {
    id: 'entry-level-friendly',
    name: 'Entry Level Friendly',
    description: 'Approachable and enthusiastic for recent graduates',
    category: 'entry-level',
    style: {
      fontSize: '11pt',
      fontFamily: 'Arial, sans-serif',
      lineHeight: '1.6',
      paragraphSpacing: '1.1rem',
      headerStyle: 'modern',
      layout: 'standard',
    },
    sections: {
      header: true,
      date: true,
      recipient: true,
      salutation: true,
      opening: true,
      body: true,
      closing: true,
      signature: true,
    },
    tone: 'enthusiastic',
  },
  {
    id: 'minimal-clean',
    name: 'Minimal Clean',
    description: 'Minimalist design focusing on content',
    category: 'professional',
    style: {
      fontSize: '11pt',
      fontFamily: 'Helvetica, sans-serif',
      lineHeight: '1.6',
      paragraphSpacing: '1.2rem',
      headerStyle: 'minimal',
      layout: 'standard',
    },
    sections: {
      header: true,
      date: false,
      recipient: true,
      salutation: true,
      opening: true,
      body: true,
      closing: true,
      signature: true,
    },
    tone: 'conversational',
  },
  {
    id: 'startup-dynamic',
    name: 'Startup Dynamic',
    description: 'Modern and energetic for fast-paced startups',
    category: 'creative',
    style: {
      fontSize: '10.5pt',
      fontFamily: 'Inter, sans-serif',
      lineHeight: '1.5',
      paragraphSpacing: '1rem',
      headerStyle: 'modern',
      layout: 'sidebar',
    },
    sections: {
      header: true,
      date: false,
      recipient: true,
      salutation: true,
      opening: true,
      body: true,
      closing: true,
      signature: true,
    },
    tone: 'enthusiastic',
  },
];

export function getTemplateById(id: string): CoverLetterTemplate | undefined {
  return coverLetterTemplates.find(template => template.id === id);
}

export function getTemplatesByCategory(category: string): CoverLetterTemplate[] {
  return coverLetterTemplates.filter(template => template.category === category);
}
